name: Build SDKs on branch push

on:
  push:
    # Set this to the branch of the repository that the `main` Stainless branch
    # of your project gets its OpenAPI spec from. This is usually the default
    # branch of your repository.
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

env:
  OAS_PATH: openapi.yml
  STAINLESS_ORG: meorphis-test
  STAINLESS_PROJECT: fake-stainless
  FAIL_ON: "error" # "note" | "warning" | "error" | "fatal" | "never"
  COMMIT_MESSAGE: "feat(api): update api"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run build
        uses: stainless-api/stainless-api/upload-openapi-spec-action@bead5be8bc72af1de6751fab77ed03d176212abf
        with:
          stainless_api_key: ${{ secrets.STAINLESS_API_KEY }}
          org: ${{ env.STAINLESS_ORG }}
          project: ${{ env.STAINLESS_PROJECT }}
          oas_path: ${{ env.OAS_PATH }}
          config_path: ${{ env.CONFIG_PATH }}
          commit_message: ${{ env.COMMIT_MESSAGE }}
          fail_on: ${{ env.FAIL_ON }}